// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqasnuenammuztqrtvjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxYXNudWVuYW1tdXp0cXJ0dmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDM0NjcsImV4cCI6MjA1NzI3OTQ2N30.vsuz-vRDryIWtjEZwYNpOghVLc3ui06OIOH8dBOYgb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);